# Site settings
title: VZW Crescendo Zottegem
email:
description: > # this means to ignore newlines until "baseurl:"

twitter_username:
github_username:

# Build settings
markdown: kramdown

include:
  - _events
  - _albums

collections:
  events:
    permalink: /_events/:path.html
  albums:
    permalink: /_albums/:path.html
